name: Run Unit Tests

on:
  push:
    branches:
      - task-1
  pull_request:
    branches:
      - task-1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"  # use your project Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pyarrow fastparquet  # Ensure parquet support

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest tests/ --maxfail=1 --disable-warnings -q
